window.GAMEVAULT_CONFIG = {
  SUPABASE_URL: 'https://cqzfxlbcewobzrrhqgfy.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxemZ4bGJjZXdvYnpycmhxZ2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1ODkxODcsImV4cCI6MjEwNjE2NTE4N30.AsyDtvWY_UhyXZdgW_3ceRwEwZuw9xfyJmceXiLq2ns',
};
